// Helper functions for file management

/**
 * Thumbnail generated by Google Drive, or '' (the caller then shows the file-type icon)
 */
export const generateThumbnailUrl = (thumbnailLink?: string | null): string => thumbnailLink || '';

/**
 * Get file type icon color based on extension
 * @param fileType - File extension
 * @returns Color class for the file icon
 */
export const getFileTypeColor = (fileType: string): string => {
    const colors: Record<string, string> = {
        'pdf': 'text-red-500',
        'doc': 'text-blue-500',
        'docx': 'text-blue-500',
        'xls': 'text-green-600',
        'xlsx': 'text-green-600',
        'ppt': 'text-orange-500',
        'pptx': 'text-orange-500',
        'txt': 'text-gray-500',
        'zip': 'text-yellow-600',
        'rar': 'text-yellow-600',
    };

    return colors[fileType.toLowerCase()] || 'text-gray-400';
};

/**
 * Get color scheme for file category badges
 * @param category - File category (Cours, TD, TP, EXAM, Autre)
 * @returns Object with bg and text color classes
 */
export const getFileCategoryColor = (category: string): { bg: string; text: string } => {
    const colors: Record<string, { bg: string; text: string }> = {
        'Cours': { bg: 'bg-accent-100', text: 'text-accent-800' },
        'TD': { bg: 'bg-atlas-100', text: 'text-atlas-800' },
        'TP': { bg: 'bg-gold-100', text: 'text-gold-800' },
        'EXAM': { bg: 'bg-red-100', text: 'text-red-800' },
        'Autre': { bg: 'bg-cream-300/60', text: 'text-atlas-700' },
    };

    return colors[category] || colors['Autre'];
};

/**
 * Format file size in human-readable format
 * @param bytes - File size in bytes
 * @returns Formatted string (e.g., "1.5 MB")
 */
export const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(2) + ' KB';
    if (bytes < 1024 * 1024 * 1024) return (bytes / (1024 * 1024)).toFixed(2) + ' MB';
    return (bytes / (1024 * 1024 * 1024)).toFixed(2) + ' GB';
};
